apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-microservice
  namespace: devops-prod
  labels:
    app: devops-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-microservice
  template:
    metadata:
      labels:
        app: devops-microservice
    spec:
      containers:
      - name: web
        image: devops-microservice:v1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
